import CustomFooter from '@/components/CustomFooter'
import BreadCrumbs from '@/components/BreadCrumbs'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{
        <>
          <BreadCrumbs />
          {children}
          <CustomFooter />
        </>
      }</body>

    </html>
  )
}
